---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Pet-Store
  description: The place to be, for your pet shopping needs
  annotations:
    github.com/project-slug: abdulkhadar-Capgemini/TestNodejs
    jenkins.io/job-full-name: TF-22-02-2023
  links:
    - url: https://backstage.io/plugins/
      title: Backstage Plugins
      icon: dashboard
  tags:
    - microservices
spec:
  type: service
  owner: abdul.azeez@capgemini.com
  lifecycle: production
  system: Pet eStore
  dependsOn: 
    - component:default/example-website
    - resource:default/petstore-db
  providesApis:
    - Pet-eStore-APIs
---
apiVersion: backstage.io/v1beta1
kind: API
metadata:
  name: Pet-eStore-APIs
  description: The API collection provides all the API's related to Pet eStore
  labels:
    owner: Pet-Store-Team
spec:
  type: openapi
  owner: abdul.azeez@capgemini.com
  lifecycle: experimental
  definition:
    $text: https://petstore.swagger.io/v2/swagger.json
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: petstore-db
  description: Stores petstore details
spec:
  type: database
  owner: petstoreDB-team
  system: petstore-DB
