apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "eShopOnDotNet"
  description: The place to be, for your shopping needs
  annotations:
    github.com/project-slug: abdulkhadar-Capgemini/TestNodejs
    jenkins.io/job-full-name: TF-22-02-2023
  links:
    - url: https://backstage.io/plugins/
      title: Backstage Plugins
      icon: dashboard
  tags:
    - microservices
spec:
  type: service
  owner: abdul.azeez@capgemini.com
  lifecycle: production
  system: eContainer Shop1
  providesApis:
    - hello-world    
  consumesApis:
    - starwars-graphql
    - streetlights
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: hello-world
  description: Hello World API
spec:
  system: systemA
  type: openapi
  lifecycle: production
  owner: abdul.azeez@capgemini.com
  definition: |
  openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /greeting:
    get:
      tags:
      - greeting-controller
      operationId: greeting
      parameters:
      - name: name
        in: query
        required: false
        schema:
          type: string
          default: World
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Greeting'
components:
  schemas:
    Greeting:
      type: object
      properties:
        id:
          type: integer
          format: int64
        content:
          type: string
