apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: eShopOnDotNet
  annotations:
    github.com/project-slug: abdulkhadar-Capgemini/eShopOnDotNet
spec:
  type: other
  lifecycle: unknown
  owner: guests