apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "eShopOnDotNet"
  description: The place to be, for your shopping needs
  annotations:
    github.com/project-slug: abdulkhadar-Capgemini/TestNodejs
    jenkins.io/job-full-name: TF-22-02-2023
    backstage.io/techdocs-ref: dir:.
  links:
    - url: https://backstage.io/plugins/
      title: Backstage Plugins
      icon: dashboard
  tags:
    - dotnet-microservices
spec:
  type: service
  owner: abdul.azeez@capgemini.com
  lifecycle: production
  system: eContainer Shop
