site_name: Pet Shop Docs
site_url: https://www.mkdocs.org/
site_description: Pet Shop Project Documentation.
site_author: MkDocs Team

nav:
    - Home: index.md

plugins:
  - techdocs-core
  - mkdocstrings:
    handlers:
      python:
        options:
          docstring_section_style: list
          members_order: source
          show_root_heading: true
          show_source: false
          show_signature_annotations: true
