site_name: Pet Shop Docs
site_url: https://www.mkdocs.org/
site_description: Pet Shop Project Documentation.
site_author: MkDocs Team

repo_url: https://github.com/mkdocs/mkdocs/
edit_uri: blob/master/docs/

theme:
    name: mkdocs
    locale: en
    analytics: {gtag: 'G-274394082'}
    highlightjs: true
    hljs_languages:
        - yaml
        - django

nav:
    - Home: index.md

markdown_extensions:
    - toc:
        permalink: 
    - attr_list
    - def_list
    - tables
    - pymdownx.highlight:
        use_pygments: false
    - pymdownx.snippets
    - pymdownx.superfences
    - callouts
    - mdx_gh_links:
        user: mkdocs
        repo: mkdocs
    - mkdocs-click

copyright: Copyright &copy; 2014 <a href="https://twitter.com/_tomchristie">Tom Christie</a>, Maintained by the <a href="/about/release-notes/#maintenance-team">MkDocs Team</a>.
